[Servidor]
#url = https://api-sistema-frfeh8g2h5cgduab.canadacentral-01.azurewebsites.net/
url = https://backendxurlex-production.up.railway.app

#ip_servidor = 192.168.1.254
#puerto = 3000
#https = false

[IpLicenciaBackend]
#urlLicencia = https://api-licencias-iurix-bgaea7bybdadhkca.canadacentral-01.azurewebsites.net/ 
urlLicencia = https://licenciaxurlexbackend-production.up.railway.app

#Esto es en local
#ip = 192.168.1.254
#puerto = 7140
#https = false

[Cliente]
modo = local

[Auth]
mode = required

; valores: off | optional | required

#EN AZURE

#[Servidor]
#ip_servidor = api-sistema-iurix.azurewebsites.net
#puerto = 443
#https = true

#[IpLicenciaBackend]
#ip = api-licencias-iurix.azurewebsites.net
#puerto = 443
#https = true

#[Cliente]
#modo = nube


