[Servidor]
#url = https://api-sistema-frfeh8g2h5cgduab.canadacentral-01.azurewebsites.net/
url = https://api.render.com/deploy/srv-daj3361594qs73alrai0?key=5MadkLs10gc
#ip_servidor = 192.168.1.254
puerto = 3000
https = false

[IpLicenciaBackend]
#urlLicencia = https://api-licencias-iurix-bgaea7bybdadhkca.canadacentral-01.azurewebsites.net/ 
urlLicencia = licenciaxurlexbackend.railway.internal
#ip = 192.168.1.254
puerto = 7140
https = false

[Cliente]
modo = local

[Auth]
mode = required

; valores: off | optional | required

#EN AZURE

#[Servidor]
#ip_servidor = api-sistema-iurix.azurewebsites.net
#puerto = 443
#https = true

#[IpLicenciaBackend]
#ip = api-licencias-iurix.azurewebsites.net
#puerto = 443
#https = true

#[Cliente]
#modo = nube
